### ISSUE TITLE
Checklist Listing All small issues

### ISSUE THREAD

**Issue by Lakshyadevelops** [Lakshyadevelops/ImageTransform#3]
- [x]  Input Image not letting window be resized smaller than it's size
- [x] Unhandled exception at 0x00007FFBE9F2531C in ImageTransform.exe: Microsoft C++ exception: cv::Exception at memory location 0x0000003B2AEF8340.        `cv::cvtColor(img, img, cv::COLOR_BGR2RGB);`
- [x] Implement Enum
- [x] Handle Input for unsupported data type(non image)
- [x] activate CUDA Lazy Loading
- [ ] Remove Default Icon
- [ ] Move stuff to heap stack limit warning being thrown
- [ ] UI responsive when processing. Move UI to separate thread
